# Settings for the "waiting room" world
wait:
  # Name of the world
  world: wait

  # Coordinates
  x: 0
  y: 128
  z: 0

# Whether Slate should disable hunger, damage etc... outside of games.
# Set to false if your server uses plugins that don't depend on Slate.
slateOnly: true
